chore: add setup for forked tests
MultiMessageAggregation/multibridge pull request #37
Opened 2023-07-21 10:35 UTC by sujithsomraaj

related to #26

- added forked unit tests across four different chains (BSC, ETH, ARB, POLYGON)
- added pigeon helpers for (CELER & HYPERLANE)

basic tests are enough to test the new features to be added. later will add more bridges to the test suite to assert all the adapters.

2023-07-21 21:22 UTC, ermyas commented on test/Setup.t.sol
> +        CelerReceiverAdapter(contractAddress[42161][bytes("CELER_RECEIVER_ADAPTER")]).updateSenderAdapter(srcChain, senderAdapters);
nit: Could this be in a `for` loop, as done above when setting the hyperplane adapters for consistency and to make it easier as new chains are added?

2023-07-22 00:11 UTC, 0xkydo commented on test/Setup.t.sol
> +    address constant ARB_CELER_MSG_BUS = 0x3Ad9d0648CDAA2426331e894e980D0a5Ed16257f;
Axelar adapter is currently in its own PR https://github.com/MultiMessageAggregation/multibridge/pull/6

2023-07-22 05:01 UTC, ermyas commented on test/success-tests/BasicSendReceiveTest.t.sol
> +    /// @dev intializes the setup
nit: "intializes" -> "initializes"

2023-07-28 06:34 UTC, 0xkydo commented on test/Setup.t.sol
> +    address constant ARB_CELER_MSG_BUS = 0x3Ad9d0648CDAA2426331e894e980D0a5Ed16257f;
Makes our live easier as well

2023-07-28 06:35 UTC, 0xkydo requested changes
All lgtm, let's adopt @ermyas 's comments and merge this pr.

2023-08-03 05:58 UTC, ermyas commented
As discussed offline, closing this PR in favour of PRs #39 and #40

2023-08-03 05:58 UTC, closed without merging